### ISSUE TITLE
Newly created sessions don't have ID set

### ISSUE THREAD

**Issue by jaredr** [trek-rs/sessions#4]
The README is a bit confusing / appears to be incorrect regarding newly created sessions:

```
let store = Arc::new(CustomStore::new());

let id = format!("id.{}", 0);                   // Generates an UID
let store = store.clone();
let session = store.get(&id).await.unwrap();    // Fresh Session

session.id().unwrap();                          // ""
// ^^^ The README correctly notes that the ID is not set for a newly created session here.

session.status().unwrap();                      // SessionStatus::Created
// [... sets some fields, but notably does not set the ID ...]

session.save().await;                           // Ok(())

let session = store.get(&id).await.unwrap();    // Matches Session
// This does not appear to actually match the previous session. That session has some random ID.
```

To match the current behavior, I believe the README needs to show the session being manually set to the fetched ID with `session.set_id(id).unwrap();` sometime before the `save()`.

That said, I'm not sure this API feels right. I've already told the library what ID I expect. It was a bit surprising to me that the session I got back had to be manually updated to have the ID I'd already asked for. Maybe if I'd gotten the session through something like `store.create_session()` or something where I wasn't already providing an ID it would make more sense? Alternatively, if `session.save()` yielded the saved ID on success instead of just `()`, it'd be more obvious that something might've changed.

**Comment by fundon** [comment]
You are right, more notes need to be added.

Gets a session by ID, if the ID is already exists in the store, returns session and includes ID. If not matches, returns fresh session and session ID is empty string.

If a session is fresh, when saving it, store will generate an new ID for it. See https://github.com/trek-rs/sessions/blob/master/src/session.rs#L149-L157. Lazy generate ID.

After saved `session.save()`, we can use `session.id()` to get ID.

I will update the README and I'm currently working on [rwlock](https://github.com/trek-rs/sessions/tree/rwlock) branch. 

Thank you very much.
