### ISSUE TITLE
session.save().await take forever on arm-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by smmoosavi** [trek-rs/sessions#5]
I tried to run my rust program on a raspberry pi zero, which has `arm-unknown-linux-gnueabi` architecture. but `session.save().await` take forever and never ends.

```
let p = session.save();
println!("login mutation, before wait");
let r = p.await;
println!("login mutation, after wait"); // never executed
```
I used `MemoryStore`.

**Comment by fundon** [comment]
Which rust version?

**Comment by smmoosavi** [comment]
```
rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by smmoosavi** [comment]
I used a newer rust version with `arm-unknown-linux-musleabi` target, and the problem was fixed for me.
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
```
